export const GOLD_CLOB_ABI = [
  {
    inputs: [
      { internalType: "address", name: "admin", type: "address" },
      { internalType: "address", name: "marketOperator", type: "address" },
      { internalType: "address", name: "oracle", type: "address" },
      { internalType: "address", name: "treasury_", type: "address" },
      { internalType: "address", name: "marketMaker_", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "duelKey", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "marketKey", type: "bytes32" },
      { indexed: false, internalType: "uint8", name: "marketKind", type: "uint8" },
    ],
    name: "MarketCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "marketKey", type: "bytes32" },
      { indexed: false, internalType: "uint64", name: "makerOrderId", type: "uint64" },
      { indexed: false, internalType: "uint64", name: "takerOrderId", type: "uint64" },
      { indexed: false, internalType: "uint256", name: "matchedAmount", type: "uint256" },
      { indexed: false, internalType: "uint16", name: "price", type: "uint16" },
    ],
    name: "OrderMatched",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "marketKey", type: "bytes32" },
      { indexed: true, internalType: "uint64", name: "orderId", type: "uint64" },
      { indexed: true, internalType: "address", name: "maker", type: "address" },
      { indexed: false, internalType: "uint8", name: "side", type: "uint8" },
      { indexed: false, internalType: "uint16", name: "price", type: "uint16" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "OrderPlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "marketKey", type: "bytes32" },
      { indexed: true, internalType: "uint64", name: "orderId", type: "uint64" },
    ],
    name: "OrderCancelled",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "duelKey", type: "bytes32" },
      { internalType: "uint8", name: "marketKind", type: "uint8" },
    ],
    name: "marketKey",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "duelKey", type: "bytes32" },
      { internalType: "uint8", name: "marketKind", type: "uint8" },
    ],
    name: "getMarket",
    outputs: [
      {
        components: [
          { internalType: "bool", name: "exists", type: "bool" },
          { internalType: "bytes32", name: "duelKey", type: "bytes32" },
          { internalType: "uint8", name: "status", type: "uint8" },
          { internalType: "uint8", name: "winner", type: "uint8" },
          { internalType: "uint64", name: "nextOrderId", type: "uint64" },
          { internalType: "uint16", name: "bestBid", type: "uint16" },
          { internalType: "uint16", name: "bestAsk", type: "uint16" },
          { internalType: "uint128", name: "totalAShares", type: "uint128" },
          { internalType: "uint128", name: "totalBShares", type: "uint128" },
        ],
        internalType: "struct GoldClob.Market",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "duelKey", type: "bytes32" },
      { internalType: "uint8", name: "marketKind", type: "uint8" },
      { internalType: "uint8", name: "side", type: "uint8" },
      { internalType: "uint16", name: "price", type: "uint16" },
    ],
    name: "getPriceLevel",
    outputs: [
      { internalType: "uint64", name: "headOrderId", type: "uint64" },
      { internalType: "uint64", name: "tailOrderId", type: "uint64" },
      { internalType: "uint128", name: "totalOpen", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "", type: "bytes32" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "positions",
    outputs: [
      { internalType: "uint128", name: "aShares", type: "uint128" },
      { internalType: "uint128", name: "bShares", type: "uint128" },
      { internalType: "uint128", name: "aStake", type: "uint128" },
      { internalType: "uint128", name: "bStake", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "", type: "bytes32" },
      { internalType: "uint64", name: "", type: "uint64" },
    ],
    name: "orders",
    outputs: [
      { internalType: "uint64", name: "id", type: "uint64" },
      { internalType: "uint8", name: "side", type: "uint8" },
      { internalType: "uint16", name: "price", type: "uint16" },
      { internalType: "address", name: "maker", type: "address" },
      { internalType: "uint128", name: "amount", type: "uint128" },
      { internalType: "uint128", name: "filled", type: "uint128" },
      { internalType: "uint64", name: "prevOrderId", type: "uint64" },
      { internalType: "uint64", name: "nextOrderId", type: "uint64" },
      { internalType: "bool", name: "active", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tradeTreasuryFeeBps",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tradeMarketMakerFeeBps",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "winningsMarketMakerFeeBps",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "duelKey", type: "bytes32" },
      { internalType: "uint8", name: "marketKind", type: "uint8" },
      { internalType: "uint8", name: "side", type: "uint8" },
      { internalType: "uint16", name: "price", type: "uint16" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "placeOrder",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "duelKey", type: "bytes32" },
      { internalType: "uint8", name: "marketKind", type: "uint8" },
      { internalType: "uint64", name: "orderId", type: "uint64" },
    ],
    name: "cancelOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "duelKey", type: "bytes32" },
      { internalType: "uint8", name: "marketKind", type: "uint8" },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "duelKey", type: "bytes32" },
      { internalType: "uint8", name: "marketKind", type: "uint8" },
    ],
    name: "syncMarketFromOracle",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
