import { type UiLocale } from "@hyperbet/ui/i18n";

export function getModelsMarketCopy(locale: UiLocale) {
    if (locale === "zh") {
        return {
            pending: "待定",
            emDash: "—",
            loadingModelsMarket: "正在加载模型市场…",
            noModelsMatched: "当前筛选条件下没有匹配的模型。",
            unnamedModel: "未命名模型",
            unknown: "未知",
            unknownProvider: "未知提供方",
            active: "活跃",
            closeOnly: "仅平仓",
            archived: "已归档",
            oracleStale: "预言机过期",
            modelPerps: "模型永续",
            trackedModels: "追踪模型",
            aggregateOi: "总未平仓",
            oracleBasis: "预言机基准",
            solanaOnly: "仅限 Solana",
            switchToSolana: "切换到 Solana",
            models: "模型",
            searchModels: "搜索模型",
            updated: (value: string) => `更新于 ${value}`,
            rank: "排名",
            model: "模型",
            provider: "提供方",
            winLoss: "胜/负",
            index: "指数",
            longOi: "多头 OI",
            shortOi: "空头 OI",
            funding: "资金费率",
            status: "状态",
            yourPosition: "你的仓位",
            openInterest: "未平仓",
            insurance: "保险池",
            oracleHistory: "预言机历史",
            currentOracle: (value: string, stale: boolean) =>
                `当前预言机 ${value}${stale ? " · 已过期" : ""}`,
            oracleHistoryError: (message: string) => `加载预言机历史失败：${message}`,
            loadingOracleHistory: "正在加载标准预言机历史…",
            waitingForSnapshots: "等待该模型的 keeper 快照。",
            skill: "技能",
            rankLabel: (value: number) => `排名 #${value}`,
            positionEntry: (value: string) => `开仓 ${value}`,
            positionMargin: (value: string) => `保证金 ${value}`,
            pnl: "盈亏",
            closePosition: "平仓",
            trade: (name: string) => `交易 ${name}`,
            marketId: (value: number) => `市场 #${value}`,
            pendingOracle: "等待预言机",
            collateral: "抵押（SOL）",
            leverage: "杠杆",
            positionSize: "仓位规模",
            estLongEntry: "预计多头开仓价",
            estShortEntry: "预计空头开仓价",
            longAction: (name: string) => `做多 ${name}`,
            shortAction: (name: string) => `做空 ${name}`,
            awaitingOracle: "等待新的预言机更新。",
            closeOnlyMarket: "当前市场仅允许平仓。",
            archivedMarket: "当前市场已归档。",
            selectModel: "选择一个模型进行查看和交易。",
            failedToLoadModelsMarketData: "加载模型市场数据失败",
            failedToLoadOracleHistory: "加载预言机历史失败",
            switchDemoToSolana: "请切换到 Solana 以交易模型永续。",
            connectWalletToTrade: "连接 Solana 钱包后即可交易模型永续。",
            walletCannotSign: "钱包无法签名交易。",
            marketNotAccepting: "该模型市场当前不接受新仓位。",
            waitingOnOracle: "该模型市场正在等待新的预言机更新。",
            marketArchived: "该模型市场已归档。",
            submitting: (direction: string, name: string) => `正在提交 ${direction} ${name}`,
            opening: (leverage: number, direction: string, name: string) =>
                `正在以 ${leverage}x ${direction} ${name}`,
            opened: (direction: string, name: string) => `已开 ${direction} ${name}`,
            openedToast: (direction: string, name: string) => `已对 ${name} 建立${direction}仓位`,
            closingPosition: (name: string) => `正在平掉 ${name} 仓位`,
            closedPosition: (name: string) => `已平掉 ${name} 仓位`,
            transactionFailed: "交易失败",
            stageBuilding: "构建交易",
            stageBlockhash: "获取区块哈希",
            stageSigning: "签名交易",
            stageSending: "发送交易",
            stageConfirming: "确认交易",
            directionLong: "多头",
            directionShort: "空头",
        };
    }

    return {
        pending: "pending",
        emDash: "—",
        loadingModelsMarket: "Loading models market…",
        noModelsMatched: "No models matched the current filter.",
        unnamedModel: "Unnamed model",
        unknown: "Unknown",
        unknownProvider: "Unknown provider",
        active: "ACTIVE",
        closeOnly: "CLOSE ONLY",
        archived: "ARCHIVED",
        oracleStale: "Oracle Stale",
        modelPerps: "Model Perps",
        trackedModels: "Tracked Models",
        aggregateOi: "Aggregate OI",
        oracleBasis: "Oracle Basis",
        solanaOnly: "Solana-only",
        switchToSolana: "Switch To Solana",
        models: "Models",
        searchModels: "Search models",
        updated: (value: string) => `Updated ${value}`,
        rank: "Rank",
        model: "Model",
        provider: "Provider",
        winLoss: "W/L",
        index: "Index",
        longOi: "Long OI",
        shortOi: "Short OI",
        funding: "Funding",
        status: "Status",
        yourPosition: "Your Position",
        openInterest: "Open Interest",
        insurance: "Insurance",
        oracleHistory: "Oracle History",
        currentOracle: (value: string, stale: boolean) =>
            `Current oracle ${value}${stale ? " · stale" : ""}`,
        oracleHistoryError: (message: string) =>
            `Failed to load oracle history: ${message}`,
        loadingOracleHistory: "Loading canonical oracle history…",
        waitingForSnapshots: "Waiting for keeper snapshots for this model.",
        skill: "Skill",
        rankLabel: (value: number) => `Rank #${value}`,
        positionEntry: (value: string) => `Entry ${value}`,
        positionMargin: (value: string) => `Margin ${value}`,
        pnl: "PnL",
        closePosition: "Close Position",
        trade: (name: string) => `Trade ${name}`,
        marketId: (value: number) => `Market #${value}`,
        pendingOracle: "Pending oracle",
        collateral: "Collateral (SOL)",
        leverage: "Leverage",
        positionSize: "Position Size",
        estLongEntry: "Est. Long Entry",
        estShortEntry: "Est. Short Entry",
        longAction: (name: string) => `Long ${name}`,
        shortAction: (name: string) => `Short ${name}`,
        awaitingOracle: "Awaiting fresh oracle update.",
        closeOnlyMarket: "Close-only market.",
        archivedMarket: "Archived market.",
        selectModel: "Select a model to inspect and trade.",
        failedToLoadModelsMarketData: "Failed to load models market data",
        failedToLoadOracleHistory: "Failed to load oracle history",
        switchDemoToSolana: "Switch the demo to Solana to trade model perps.",
        connectWalletToTrade: "Connect a Solana wallet to trade model perps.",
        walletCannotSign: "Wallet cannot sign transactions.",
        marketNotAccepting: "This model market is not accepting new positions.",
        waitingOnOracle: "This model market is waiting on a fresh oracle update.",
        marketArchived: "This model market has been archived.",
        submitting: (direction: string, name: string) =>
            `Submitting ${direction} ${name}`,
        opening: (leverage: number, direction: string, name: string) =>
            `Opening ${leverage}x ${direction} on ${name}`,
        opened: (direction: string, name: string) => `Opened ${direction} ${name}`,
        openedToast: (direction: string, name: string) =>
            `Opened ${direction} on ${name}`,
        closingPosition: (name: string) => `Closing ${name} position`,
        closedPosition: (name: string) => `Closed ${name} position`,
        transactionFailed: "Transaction failed",
        stageBuilding: "building transaction",
        stageBlockhash: "fetching blockhash",
        stageSigning: "signing transaction",
        stageSending: "sending transaction",
        stageConfirming: "confirming transaction",
        directionLong: "long",
        directionShort: "short",
    };
}
